# GENERAL
title: Muhack
description: "Il primo hackerspace bresciano, nato per promuovere la cultura open-source tramite la condivisione di idee, risorse ed esperienze!"
baseurl: ""
url: "https://muhack.org/"
# SOCIAL
facebook-username: muhackIT
twitter-username: muhackIT
github-username: muhack
youtube-username: UC3NrDI9TYPBYz6pbUl3tqcA
email: info@muhack.org
# GOOGLE ANALYTICS
# google-analytics-id:
# BUILD SETTINGS
highlighter: rouge
# PERMALINKS
permalink: /:categories/:title/
relative_permalinks: false
# PAGINATION
paginate: 5
paginate_path: ":num"
# GEMS
plugins: [jekyll-paginate, jekyll-feed]
